### ISSUE TITLE
debian 12

### ISSUE THREAD

**Issue by gnu-like** [onboard-osk/onboard#5]
onboard $ python3 setup.py build
To build Onboard you need https://launchpad.net/python-distutils-extra

but python3-distutils-extra (2.50) is installed in my os

**Comment by gnu-like** [comment]
I've installed distutils-extra-python 2.39.2 by `pip install distutils-extra-python` after insalling onboard :

```
$ onboard
Traceback (most recent call last):
  File "/usr/local/bin/onboard", line 32, in <module>
    from Onboard.Exceptions import chain_handler
ModuleNotFoundError: No module named 'Onboard'
```
[onboard.txt](https://github.com/user-attachments/files/17680224/onboard.txt)

according log I sent onboard not installed `WARNING: the following files are not recognized by DistUtilsExtra.auto:`

**Comment by gnu-like** [comment]
according log I  sent onboard not installed `WARNING: the following files are not recognized by DistUtilsExtra.auto:`

**Comment by dr-ni** [comment]
> I've installed distutils-extra-python 2.39.2 by `pip install distutils-extra-python` after insalling onboard :
> 
> ```
> $ onboard
> Traceback (most recent call last):
>   File "/usr/local/bin/onboard", line 32, in <module>
>     from Onboard.Exceptions import chain_handler
> ModuleNotFoundError: No module named 'Onboard'
> ```
> 
> [onboard.txt](https://github.com/user-attachments/files/17680224/onboard.txt)
> 
> according log I sent onboard not installed `WARNING: the following files are not recognized by DistUtilsExtra.auto:`

On newer systems pip is only possible in a virtual environment so I cannot give you support for that. Installation with apt is working (see README)

All thees warnings ar normal (not used files) and can be ignored

**Comment by dr-ni** [comment]
Did you solve the problem?

**Comment by gnu-like** [comment]
Hello , I installed your onboard but not worked
````
Traceback (most recent call last):
  File "/usr/local/bin/onboard", line 32, in <module>
    from Onboard.Exceptions import chain_handler
ModuleNotFoundError: No module named 'Onboard'
````

[log.txt](https://github.com/user-attachments/files/19015801/log.txt)

**Comment by gnu-like** [comment]
installing with apt works on debian 12

**Comment by dr-ni** [comment]
your log.txt is looking fine. Theese warnings are no problem.

can you try `onboard --version `

**Comment by gnu-like** [comment]
> your log.txt is looking fine. Theese warnings are no problem.
> 
> can you try `onboard --version `

seems fine but onboard is not installing  `No module named 'Onboard'` even its icon missing in application menu , Did you check it in debian12?

**Comment by dr-ni** [comment]
python3 setup.py clean
python3 setup.py build
    
sudo tools/install_gsettings_schema
sudo python3 setup.py install


or

./build_debs.sh
./apt_install_debs.sh

**Comment by dr-ni** [comment]
I have also a missing icon in raspberrypi os but the setup..py install is working
Can you supply some more info for the missing module

**Comment by gnu-like** [comment]
I removed    ` sudo apt purge onboard onboard-common onboard-data` git pull , but same error 

[log.txt](https://github.com/user-attachments/files/19039995/log.txt)

**Comment by gnu-like** [comment]
maybe this error `WARNING: the following files are not recognized by DistUtilsExtra.auto:` is caused not install rightly
thank you I back apt install onboard

**Comment by dr-ni** [comment]
and again `onboard --version`

**Comment by dr-ni** [comment]
you should build your log like this:`sudo python3 setup.py install >log.txt 2>&1` that I can see all output

**Comment by gnu-like** [comment]
I send all output 

[log1.txt](https://github.com/user-attachments/files/19041850/log1.txt)

**Comment by gnu-like** [comment]
It works ,finally I found problem.
onboard --version
1.4.2

**Comment by lgoio** [comment]
Please leave a short explanation for others who might encounter the same issue.

**Comment by gnu-like** [comment]
> Please leave a short explanation for others who might encounter the same issue.

python modules with installing pip is better create a virtual environment , I had virtualenv and conflicted with `sudo apt install python3-distutils-extra `and `sudo apt install python3-setuptools` so I removed python virtual environment

**Comment by dr-ni** [comment]
ok fine :-)
Do you have still the missing icon when using the debs?

**Comment by gnu-like** [comment]
> ok fine :-) Do you have still the missing icon when using the debs?

No, after installing did not show icon I changed system icon and now appear 😂

**Comment by dr-ni** [comment]
can you explain it more detailed?  Which icon did you change - and where you changed that?

**Comment by gnu-like** [comment]
> can you explain it more detailed? Which icon did you change - and where you changed that?

sure ,I use Gnome desktop , Adwaita icon changed to gnome icon with _GNOME Tweaks_ program .

**Comment by dr-ni** [comment]
do you have screenshots before and after change?

**Comment by gnu-like** [comment]
> do you have screenshots before and after change?

unfortunately I didn't  take screenshot before

**Comment by gnu-like** [comment]
Thank you so much , you developed the onboard program for debian

**Comment by dr-ni** [comment]
We only continue development…

can you make a screenshot and draw an arrow onto the icon you changed?

**Comment by gnu-like** [comment]
> We only continue development…
> 
> can you make a screenshot and draw an arrow onto the icon you changed?

![Image](https://github.com/user-attachments/assets/5949efdc-dc83-41bb-8743-6753e00730e8)

**Comment by dr-ni** [comment]
where is the icon on your screen? In the systray? Is the icon the onboard icon?

**Comment by gnu-like** [comment]
> where is the icon on your screen? In the systray? Is the icon the onboard icon?

now , there is no problem , onboard icon is on top panel (sys tray) and applications menu

![Image](https://github.com/user-attachments/assets/8a8201a6-d237-44ab-95c0-a950f2109944)

**Comment by dr-ni** [comment]
did you install onboard over python setup.py script or the apt_install_debs.sh

**Comment by gnu-like** [comment]
python setup.py

**Comment by dr-ni** [comment]
if I use setup.py - the icon is in the tray - if I uninstall all (see README) and install apt_install_debs.sh it is missing

can you please check this?

**Comment by gnu-like** [comment]
sure I'll check it and announce you

**Comment by lgoio** [comment]
If the `gnome-shell` command is not detected, the `gnome-shell-extension-onboard` will not be installed:  

```bash
which gnome-shell >/dev/null 2>&1 && echo "GNOME Shell is installed." || echo "GNOME Shell is not installed."
```

**Comment by dr-ni** [comment]
I do not use gnome-shell

**Comment by lgoio** [comment]
I suspect that some files are missing in /usr/share/onboard/. @dr-ni, could you check the differences using meld?

**Comment by dr-ni** [comment]
@lgoio 
do you mean `/usr/local/share/onboard` ?

**Comment by dr-ni** [comment]
![Image](https://github.com/user-attachments/assets/5e89ef98-6cdd-495b-bc6a-076fe9dd437e)

**Comment by dr-ni** [comment]
@lgoio 

with setup.py all is installed in:
/usr/local/share/onboard

with apt_install_debs.sh in:
/usr/share/onboard

Is this the problem?

**Comment by gnu-like** [comment]
> if I use setup.py - the icon is in the tray - if I uninstall all (see README) and install apt_install_debs.sh it is missing
> 
> can you please check this?

apt_install_debs.sh script has problems I cd onboard/build/debs and couldn't install deb package , I share logs

[log_apt.txt](https://github.com/user-attachments/files/19043987/log_apt.txt)

[log_deb.txt](https://github.com/user-attachments/files/19043988/log_deb.txt)

[log2.txt](https://github.com/user-attachments/files/19043989/log2.txt)

**Comment by dr-ni** [comment]
you have to cd to ~/onboard
then ./apt_install_debs.sh

**Comment by lgoio** [comment]
if /usr/local/share/onboard is still present after installing via apt the install_dir in settings.py is miss configured to /usr/local/share/onboard and should be /usr/share/onboard.
settings_*.ui are not loaded correct from LoadUI.

The setup.py uninstall command doen't work as expected:
sudo python setup.py uninstall
removing directory 'share/onboard'
Failed to remove 'share/onboard':[Errno 2] No such file or directory: 'share/onboard'

**Comment by gnu-like** [comment]
> you have to cd to ~/onboard then ./apt_install_debs.sh

yes I know after getting error I tested /onboard/build/debs

**Comment by gnu-like** [comment]
Onboard 1.4.2 Debian packages successfully built and saved in: /home/debian/onboard/build/debs

but apt_install_debs.sh script couldn't find package 

E: Failed to fetch file:/home/debian/onboard/build/debs/./Packages  File not found - /home/debian/onboard/build/debs/./Packages (2: No such file or directory)
E: Some index files failed to download. They have been ignored, or old ones used instead.
Reading package lists...

if we want to install debs by `sudo apt install ./onboard_1.4.2-1_amd64.deb` don't recognize new version 

onboard : Depends: onboard-common (>= 1.4.2-1) but 1.4.1-5 is to be installed

**Comment by dr-ni** [comment]
@lgoio this is my deb installation (icon missing)
```
uwe@rp64:~ $ ls /usr/local/share/onboard
ls: Zugriff auf '/usr/local/share/onboard' nicht möglich: Datei oder Verzeichnis nicht gefunden
uwe@rp64:~ $ ls /usr/share/onboard
emojione          scripts                     settings.ui
layouts           settings_docking_dialog.ui  themes
layoutstrings.py  settings_scanner_dialog.ui  tools
models            settings_theme_dialog.ui
uwe@rp64:~ $ onboard 

(onboard:5646): Gtk-WARNING **: 19:38:36.667: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
```

**Comment by dr-ni** [comment]
and with setup.py (icon is present)
```
uwe@rp64:~ $ ls /usr/local/share/onboard
emojione          scripts                     settings.ui
layouts           settings_docking_dialog.ui  themes
layoutstrings.py  settings_scanner_dialog.ui  tools
models            settings_theme_dialog.ui
uwe@rp64:~ $ ls /usr/share/onboard
ls: Zugriff auf '/usr/share/onboard' nicht möglich: Datei oder Verzeichnis nicht gefunden
uwe@rp64:~ $ onboard 

(onboard:6365): Gdk-CRITICAL **: 19:49:45.650: gdk_window_thaw_toplevel_updates: assertion 'window->update_and_descendants_freeze_count > 0' failed
```

**Comment by dr-ni** [comment]
``@gnu-like do not use `sudo apt ...`

you should use

`~/onboard/apt_install_debs.sh >log.txt 2>&1`
and post the log

@lgoio maybe the path is wrong here https://github.com/user-attachments/files/19043989/log2.txt ?

**Comment by lgoio** [comment]
I installed Onboard using `apt_install_debs.sh` and "setup.py install" on a fresh **VirtualBox Debian 12.9.0 XFCE** setup. See the screenshot :

![Image](https://github.com/user-attachments/assets/01847f84-6b23-4942-bf7c-03a91422572b)

I pushed some changes to simplify installation and uninstallation, along with various other improvements. See **README.md** for details.  

### **Installation Steps to install the Debian packages after setup.py install was called**  

#### **1. Clean existing Onboard sources**  
```bash
sudo rm -rf "$HOME/onboard/"
```

#### **2. Clone the latest source code**  
```bash
cd ~
sudo apt-get -y install git
git clone https://github.com/dr-ni/onboard.git
cd ~/onboard/
```

#### **3. Uninstall any previous installation from `setup.py`**  
```bash
sudo python3 setup.py uninstall
```

#### **4. Build the Debian packages**  
```bash
/bin/sh ./build_debs.sh
```

#### **5. Install the Debian packages**  
```bash
/bin/sh ./apt_install_debs.sh
```

**Comment by gnu-like** [comment]
In debian 12 and gnome 43.9
/bin/sh ./apt_install_debs.sh
```
~ $ onboard
Traceback (most recent call last):
  File "/usr/bin/onboard", line 36, in <module>
    ob = Onboard()
         ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Onboard/OnboardGtk.py", line 148, in __init__
    self.init()
  File "/usr/lib/python3/dist-packages/Onboard/OnboardGtk.py", line 178, in init
    config.init()
  File "/usr/lib/python3/dist-packages/Onboard/Config.py", line 486, in init
    self.load_theme()
  File "/usr/lib/python3/dist-packages/Onboard/Config.py", line 975, in load_theme
    self.apply_theme()
  File "/usr/lib/python3/dist-packages/Onboard/Config.py", line 955, in apply_theme
    theme = Theme.load(filename)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Onboard/Appearance.py", line 285, in load
    _file = open_utf8(filename)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Onboard/utils.py", line 1345, in open_utf8
    return open(filename, mode=mode, encoding="UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

```
then I did `/bin/sh ./apt_install_debs.sh "remove"`
   ```
 python3 setup.py clean
    python3 setup.py build
    sudo python3 setup.py install
```
found dconf version 0.40.0
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
Generating GSettings schema: build/share/glib-2.0/schemas/99_onboard-default-settings.gschema.override
Detected GNOME-based environment. Using gsettings...
Detected font: Cantarell
Generated GSettings override file: build/share/glib-2.0/schemas/99_onboard-default-settings.gschema.override
['data/org.onboard.gschema.xml']
['build/share/glib-2.0/schemas/99_onboard-default-settings.gschema.override']

**Comment by gnu-like** [comment]
before there was no problem with `setup.py install` in gnome

**Comment by lgoio** [comment]
I was also able to install Onboard using the **debian-live-12.0.0-amd64-gnome.iso**.  
It looks like there might be an issue with your theme settings.  
Please try resetting your Onboard configuration with the following command:  

```bash
dconf reset -f /org/onboard/
```

**Comment by gnu-like** [comment]
> I was also able to install Onboard using the **debian-live-12.0.0-amd64-gnome.iso**. It looks like there might be an issue with your theme settings. Please try resetting your Onboard configuration with the following command:
> 
> dconf reset -f /org/onboard/

I did but

```
~ $ onboard
Traceback (most recent call last):
  File "/usr/bin/onboard", line 36, in <module>
    ob = Onboard()
         ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Onboard/OnboardGtk.py", line 148, in __init__
    self.init()
  File "/usr/lib/python3/dist-packages/Onboard/OnboardGtk.py", line 178, in init
    config.init()
  File "/usr/lib/python3/dist-packages/Onboard/Config.py", line 486, in init
    self.load_theme()
  File "/usr/lib/python3/dist-packages/Onboard/Config.py", line 975, in load_theme
    self.apply_theme()
  File "/usr/lib/python3/dist-packages/Onboard/Config.py", line 955, in apply_theme
    theme = Theme.load(filename)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Onboard/Appearance.py", line 285, in load
    _file = open_utf8(filename)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Onboard/utils.py", line 1345, in open_utf8
    return open(filename, mode=mode, encoding="UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: ''

```

**Comment by dr-ni** [comment]
for my raspberrypi now both not working anymore 

[pyt-log.txt](https://github.com/user-attachments/files/19054702/pyt-log.txt)
[debs-log.txt](https://github.com/user-attachments/files/19054703/debs-log.txt)

**Comment by lgoio** [comment]
This is propably cause by 99_onboard-default-settings.gschema.override,
please pull the last changes and reinstall onboard
```
bash
git pull
sudo python3 setup.py uninstall
/bin/sh ./apt_install_debs.sh remove
# ensure every 99_onboard-default-settings.gschema.override file is deleted
sudo rm -f /usr/share/glib-2.0/schemas/99_onboard-default-settings.gschema.override
sudo rm -f /usr/local/share/glib-2.0/schemas/99_onboard-default-settings.gschema.override
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/local/share/glib-2.0/schemas/
/bin/sh ./build_debs.sh
/bin/sh ./apt_install_debs.sh
```

**Comment by lgoio** [comment]
Note: That i changed many things for debian 12 support and there is now legacy support of the gnome shell extension.

**Comment by gnu-like** [comment]
The following packages have unmet dependencies:
 onboard : Depends: acpid but it is not installable
           Recommends: gir1.2-appindicator3-0.1 but it is not installable
E: Unable to correct problems, you have held broken packages.
onboard $ sudo apt install libappindicator3-1 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'libayatana-appindicator3-1' instead of 'libappindicator3-1'
libayatana-appindicator3-1 is already the newest version (0.5.92-1).
libayatana-appindicator3-1 set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 135 not upgraded.
onboard $

**Comment by dr-ni** [comment]
[err.txt](https://github.com/user-attachments/files/19057791/err.txt)

**Comment by lgoio** [comment]
I fixed it but note that if acpid is not installed the HardwareSensorTracker is not used.

**Comment by dr-ni** [comment]
debs:

uwe@rp64:~/onboard $ onboard
Exception ignored error evaluating path:
Traceback (most recent call last):
  File "<frozen getpath>", line 660, in <module>
OSError: failed to make path absolute
Fatal Python error: error evaluating path
Python runtime state: core initialized

Current thread 0x0000007f853fc4c0 (most recent call first):
  <no Python frame>

**Comment by dr-ni** [comment]
ah ok, new terminal:

uwe@rp64:~ $ onboard
Not running on Wayland, proceeding normally.

**Comment by dr-ni** [comment]
but no icon?

![Image](https://github.com/user-attachments/assets/fa8fc039-5739-46ea-8593-80bb05f6a58e)v

**Comment by dr-ni** [comment]
after reboot:
uwe@rp64:~ $ onboard
Not running on Wayland, proceeding normally.
Traceback (most recent call last):
  File "/usr/bin/onboard", line 44, in <module>
    ob = Onboard()
         ^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Onboard/OnboardGtk.py", line 148, in __init__
    self.init()
  File "/usr/lib/python3/dist-packages/Onboard/OnboardGtk.py", line 178, in init
    config.init()
  File "/usr/lib/python3/dist-packages/Onboard/Config.py", line 486, in init
    self.load_theme()
  File "/usr/lib/python3/dist-packages/Onboard/Config.py", line 975, in load_theme
    self.apply_theme()
  File "/usr/lib/python3/dist-packages/Onboard/Config.py", line 955, in apply_theme
    theme = Theme.load(filename)
            ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Onboard/Appearance.py", line 285, in load
    _file = open_utf8(filename)
            ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/Onboard/utils.py", line 1345, in open_utf8
    return open(filename, mode=mode, encoding="UTF-8")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] Datei oder Verzeichnis nicht gefunden: ''

**Comment by dr-ni** [comment]
and python3 setup:

![Image](https://github.com/user-attachments/assets/15802209-f882-44a9-83a5-9937c4803927)

**Comment by lgoio** [comment]
The problem is an empty user install dir ~/.local/share/onboard there is now a lookup for the theme */share/onboard/theme/Classic Onboard.theme in Config.py::_get_install_dir()

**Comment by dr-ni** [comment]
ok, super debs is working now - but still no icon

**Comment by lgoio** [comment]
Looks like the font is not set correct:
#### uninstall the user install
python3 setup.py uninstall
sudo rm -f /usr/share/glib-2.0/schemas/99_onboard-default-settings.gschema.override
sudo rm -f /usr/local/share/glib-2.0/schemas/99_onboard-default-settings.gschema.override
sudo glib-compile-schemas /usr/share/glib-2.0/schemas/
sudo glib-compile-schemas /usr/local/share/glib-2.0/schemas/
dconf reset -f /org/onboard/

PS.: I removed the experimental user installation from Readme.md
cause every body is using copy paste during the installation steps this is a bad idea.

**Comment by lgoio** [comment]
python3 setup.py uninstall # without root

**Comment by dr-ni** [comment]
ok - I did uninstall

still no icon in taskbar

![Image](https://github.com/user-attachments/assets/65d1f04d-8403-428a-b7ab-2c2ac4061897)

**Comment by lgoio** [comment]
See my commit i removed every thing releated to the USER_INSTALL_DIR

**Comment by dr-ni** [comment]
no noticable improovement

**Comment by dr-ni** [comment]
I'm still wondering why the python install is with icon?

![Image](https://github.com/user-attachments/assets/77b35517-6eb1-4713-b361-97c178c42251)

**Comment by dr-ni** [comment]
maybe we should print out the path of the icon while loading...
I think the icon also did not load with all distro debs since a long time now
do you know where it is loaded?

**Comment by lgoio** [comment]
Indicator.py: class BackendGtkStatusIcon
self._status_icon = Gtk.StatusIcon(icon_name=self.icon_name)

**Comment by lgoio** [comment]
Onboard running with Debian 12.9.0 XFCE (debian-live-12.9.0-amd64-xfce.iso):

![Image](https://github.com/user-attachments/assets/24288952-c8db-4a84-b47c-1583719aae4e)

Onboard running with Debian 12.0.0 Wayland Gnome (debian-live-12.0.0-amd64-gnome.iso):

![Image](https://github.com/user-attachments/assets/60d3b08e-ec04-4ed3-b1c5-42ce6d474b7d)

**Comment by dr-ni** [comment]
is wayland catching onboard and sending events to the active window?

**Comment by lgoio** [comment]
https://github.com/user-attachments/assets/871422dd-4c2c-4f76-ac3b-8badbb09c6f5

**Comment by lgoio** [comment]
Sometimes it is not working onboard is not comming up but also on x11.

**Comment by lgoio** [comment]
Perhaps it is caused by the dbus toggle/show/hide from the gnome extension.

**Comment by dr-ni** [comment]
can you write?

**Comment by lgoio** [comment]
https://github.com/user-attachments/assets/9b5c7ae6-c44f-467d-94a7-079c2b5f3257

**Comment by lgoio** [comment]
> Sometimes it is not working onboard is not comming up but also on x11.

if Onboard is toggled by the indicator, the auto-hide feature doesn't work. This is the intended behavior because we cannot reliably determine whether there is a text field at that position that might not be recognized as such.

I tested a lot on my X11 system and i can't reconstruct that, perhapt i called "Exit Onboard" from the gnome shell extension accidentally.

**Comment by dr-ni** [comment]
do I understand it correct that you are testing all on the shell extension?
I'm only using onboard without extension

I also found out, that after
`sudo update-mime-database /usr/share/mime`
I have now also for the debs a void icon for onboard in the taskbar

![Image](https://github.com/user-attachments/assets/979857a7-b009-40e3-b8e3-d318d7be23d0)

(the black monitor)

any idea?

**Comment by lgoio** [comment]
Good news see my last commit.

**Comment by lgoio** [comment]
![Image](https://github.com/user-attachments/assets/2524e640-dda5-45af-a30f-e2756ea96898)

update-mime-database /usr/share/mime is realy slow and probably not required i added gtk-update-icon-cache, if that doesn't work please change debian/postinst and debian/postrm

**Comment by dr-ni** [comment]
the onboard icon is still not loading in the taskbar on my raspberrypi with installed debs - still only the black monitor instead - but working as expectet (right- and leftclick)
I've tried to put some printout into the code to show the path of the icon, but was not shown. Do you have an idea how I can do this for testing?

**Comment by dr-ni** [comment]
if I purge onboard in apt I can see this:

Löschen der Konfigurationsdateien von onboard (1.4.2-1) ...
Removing Onboard GSettings schema...
Updating GLib schemas...
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: No theme index file.
gtk-update-icon-cache: No theme index file.

is the index file missing?

**Comment by dr-ni** [comment]
on my other systems with working icon  I have this output:

Löschen der Konfigurationsdateien von onboard (1.4.2-1) ...
Removing Onboard GSettings schema...
Updating GLib schemas...
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.
gtk-update-icon-cache: Cache file created successfully.

**Comment by lgoio** [comment]
There is no theme index file created cause there is no icon in ubuntu-mono-dark & ubuntu-mono-light remaining.
