### ISSUE TITLE
Fedora: Building from source

### ISSUE THREAD

**Issue by haytham-med** [onboard-osk/onboard#6]
Hi, great thanks for trying to maintain this project 🌷

I'm using fedora and trying to build from source.

- `python3 ./setup.py` gives me this message:

setup.py: get_pkg_version('dconf'): pkg-config returned exit code 1

- While `python3 ./onboard` gives me this:

09:37:53.554 WARNING Config: Starting in project directory, importing local packages and extensions.
Traceback (most recent call last):
  File "/home/hay207/Downloads/source/onboard-1.4.2/./onboard", line 35, in <module>
    from Onboard.OnboardGtk import OnboardGtk as Onboard
  File "/home/hay207/Downloads/source/onboard-1.4.2/Onboard/OnboardGtk.py", line 48, in <module>
    from Onboard.Keyboard        import Keyboard
  File "/home/hay207/Downloads/source/onboard-1.4.2/Onboard/Keyboard.py", line 45, in <module>
    from Onboard.KeyboardPopups        import TouchFeedback
  File "/home/hay207/Downloads/source/onboard-1.4.2/Onboard/KeyboardPopups.py", line 256, in <module>
    class LabelPopup(KeyboardPopupDrawable):
  File "/home/hay207/Downloads/source/onboard-1.4.2/Onboard/KeyboardPopups.py", line 264, in LabelPopup
    _osk_util = osk.Util()
                ^^^^^^^^
AttributeError: module 'Onboard.osk' has no attribute 'Util'

I really need this project in my work as a doctor...

**Comment by dr-ni** [comment]
`python3 ./onboard`  is not working anymore on newer systems since python3 applications require a virtual environment. What version of fedora is used?

Please supply a full log of the setup.py output

**Comment by dr-ni** [comment]
sorry, without any info I cannot help you
